version: "3.8"

services:
  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/datacentric_db?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-network:
    restart: on-failure


  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=datacentric_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network




volumes:
  mysql-data:


networks:
  springboot-mysql-network:
    name: springboot-mysql-network
    driver: bridge